### ISSUE TITLE
Fix hook config.sh to work for 2nd-level domains

### ISSUE THREAD

**Issue by darkgamer120** [GTAXL/certdeploy#1]
Hello, your code for config.sh rewrites for 1st level domains, so domains such as cakeforce.co.uk will rewrite to co.uk.

**Comment by GTAXL** [comment]
We completely fixed this issue and much more with my own Cloudflare hook I coded up myself. :) Reach out to me before you update it. See commits https://github.com/GTAXL/certdeploy/commit/1a6aa2bcfecfc575495a6110502075eb92a2f73b and https://github.com/GTAXL/certdeploy/commit/5acdf178c5929f7206cc86718bd492c5399d797e
